"""add column is_verivied to users and password not unique

Revision ID: 389d72b85d97
Revises: 2180bf1ac8aa
Create Date: 2024-12-04 02:56:06.236277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389d72b85d97'
down_revision: Union[str, None] = '2180bf1ac8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True))
        batch_op.drop_constraint('users_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_password_key', ['password'])
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
